# PostgreSQL. Versions 9.1 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Invoces_development

production:
  <<: *default
  database: Invoces_production
  username: Invoces
  password: <%= ENV['RECEIPT_DATABASE_PASSWORD'] %>
